{
 "title": "Main metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(app_user_messages_total{application=\"whiteboard\"}[1m])",
     "legendFormat": "image load"
    },
    {
     "expr": "rate(app_user_updates_total{application=\"whiteboard\"}[1m])",
     "legendFormat": "image updates"
    }
   ]
  },
  {
   "title": "System cpu usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Logs increasing per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(logback_events_total{level=\"info\"}[1m])",
     "legendFormat": "info"
    },
    {
     "expr": "increase(logback_events_total{level=\"error\"}[1m])",
     "legendFormat": "errors"
    },
    {
     "expr": "increase(logback_events_total{level=\"warn\"}[1m])",
     "legendFormat": "warn"
    }
   ]
  },
  {
   "title": "Application ready minutes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_ready_time_seconds/60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}