name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root
            if [ ! -d collaborative_editor ]; then
              git clone https://github.com/gghost1/collaborative_editor.git
            fi
            cd collaborative_editor
            git pull origin main
            docker-compose down
            docker volume rm collaborative_editor_kafka_data || true
            docker-compose up --build -d
